name: algo-trader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - libta-lib
  - ta-lib=0.6.4
  - numpy
  - pandas
  - pytz
  - redis-py
  - pip:
      - alpaca-py>=0.28.0
      - aiohttp==3.9.5
      - python-dotenv==1.0.1
      - loguru==0.7.2
      - -r requirements-dev.txt
