name: algo-trader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - libta-lib
  - ta-lib
  - numpy
  - pandas
  - pytz
  - redis-py
  - pip:
      - alpaca-py
      - aiohttp
      - python-dotenv
      - loguru
      - -r requirements-dev.txt
